import type { UserConfig } from "@commitlint/types";

const MODULE_SCOPES = [
	"addresses",
	"announcements",
	"auth",
	"cart",
	"collections",
	"colors",
	"cron",
	"customizations",
	"dashboard",
	"discounts",
	"emails",
	"faq",
	"materials",
	"media",
	"newsletter",
	"orders",
	"payments",
	"product-types",
	"products",
	"refunds",
	"reviews",
	"skus",
	"store-settings",
	"users",
	"webhooks",
	"wishlist",
] as const;

const CROSS_CUTTING_SCOPES = [
	"a11y",
	"admin",
	"api",
	"ci",
	"config",
	"deps",
	"docs",
	"i18n",
	"lint",
	"perf",
	"prisma",
	"pwa",
	"release",
	"security",
	"seo",
	"shared",
	"shop",
	"test",
	"types",
	"ui",
] as const;

const config: UserConfig = {
	extends: ["@commitlint/config-conventional"],
	rules: {
		"type-enum": [
			2,
			"always",
			[
				"feat",
				"fix",
				"perf",
				"refactor",
				"style",
				"test",
				"docs",
				"build",
				"ci",
				"chore",
				"revert",
			],
		],
		"scope-enum": [1, "always", [...MODULE_SCOPES, ...CROSS_CUTTING_SCOPES]],
		"scope-case": [2, "always", "kebab-case"],
		"subject-case": [0],
		"subject-max-length": [2, "always", 100],
		"body-max-line-length": [1, "always", 120],
		"footer-max-line-length": [0],
	},
};

export default config;
