-- Audit schéma V4, Lot 4 — `Order.stripeChargeId` : le considérant a disparu.
--
-- La colonne a été ajoutée le 2026-08-04 (migration 20260804200000) pour UNE
-- raison, écrite noir sur blanc dans cette migration : `buildInvoiceData`
-- écrivait `payment.stripeChargeId: null` EN DUR faute de colonne à lire, et
-- cette valeur partait FIGÉE dans `Order.invoiceDataSnapshot`, canonicalisé sous
-- SHA-256 et conservé dix ans (Art. L102 B LPF).
--
-- Le snapshot a été retiré le 2026-08-05 (migration 20260805210000) : le PDF
-- archivé est désormais la seule pièce probante. Or `render-invoice-pdf.ts` ne lit
-- de `data.payment` que `paidAt` — le `stripeChargeId` n'a JAMAIS été imprimé.
-- Plus rien ne le fige, donc, et plus rien ne le lit.
--
-- État final avant retrait : 1 écrivain (`processOrderFromPaymentIntent`), 1
-- `select`, 2 recopies dans un objet transitoire jamais rendu, 0 `where`,
-- 0 `orderBy`. Les `stripeChargeId` qui subsistent dans `refund-handlers.ts` sont
-- des contextes Sentry alimentés par `charge.id` du payload Stripe — pas la
-- colonne.
--
-- Ce qu'on perd, et pourquoi c'est acceptable : le rattachement charge → commande
-- en une lecture SQL. Il reste reconstituable à tout instant depuis
-- `stripePaymentIntentId` (CONSERVÉ, `@unique`, exigé par le CHECK
-- `Order_paid_requires_stripe_proof`) via `PaymentIntent.latest_charge`.
--
-- ⚠️ CONDITION DE RÉOUVERTURE : si un snapshot de données de facture revient — ce
-- qui exigerait d'y re-verser l'identité vendeur, cf. le commentaire du modèle
-- `Order` — la colonne doit revenir AVANT lui, sinon on refige un `null` pour dix
-- ans. C'est exactement le défaut que l'ajout du 2026-08-04 corrigeait.

DROP INDEX IF EXISTS "Order_stripeChargeId_key";
ALTER TABLE "Order" DROP COLUMN "stripeChargeId";
