-- Audit schéma V4, Lot 3 — `OrderItem.skuColorHexes`.
--
-- Snapshot CSV des hex de couleur du SKU, figé au checkout. Un seul rendu dans
-- tout le dépôt : les pastilles de couleur de l'e-mail de confirmation
-- (`EmailColorSwatch`). Absent du PDF de facture, de la fiche commande admin, du
-- suivi client et de l'e-mail d'expédition — alors qu'il traversait huit couches
-- de transport (2 selects `order.constants`, `mark-as-paid`, `resend-order-email`,
-- les types webhook, `checkout-order-processing`, `checkout-post-tasks`, les types
-- e-mail).
--
-- `skuColor` — le NOM de la couleur, affiché juste à côté et imprimé sur la
-- facture (Art. 242 nonies A ann. II CGI, désignation du bien) — est CONSERVÉ.
-- Ce qui disparaît est la pastille, pas l'information de couleur.
--
-- ⚠️ CONDITION DE RÉOUVERTURE : les hex ne se dérivent pas au rendu. L'invariant 4
-- (« snapshots OrderItem figés au moment du checkout ») l'interdit — un renvoi
-- d'e-mail six mois plus tard afficherait les couleurs COURANTES du SKU, ou rien
-- si le SKU a été supprimé. Rouvrir la pastille impose donc de rouvrir la colonne
-- ET son câblage jusqu'au webhook Stripe, qui est l'émetteur de ~100 % des
-- commandes (c'était précisément le défaut corrigé à l'audit V2, Lot 5).

ALTER TABLE "OrderItem" DROP COLUMN "skuColorHexes";
