-- Lot 3 de l'audit schéma V2 (2026-08-05) — retrait des index de la tâche
-- `retry-webhooks`.
--
-- POURQUOI la tâche part. Trois systèmes de reprise se superposaient sur les
-- webhooks Stripe. La route renvoie un **500** en cas d'échec
-- (`app/api/webhooks/stripe/route.ts`), donc Stripe redélivre tout seul pendant
-- 3 jours, et chaque redélivrance ré-incrémente `attempts` (qui alimente toujours
-- l'alerte admin). Les conséquences MÉTIER, elles, sont rattrapées par les tâches
-- de réconciliation (`reconcile-invoices`, `reconcile-refunds`,
-- `sync-async-payments`). Le bouton `retry-webhooks` était le troisième étage,
-- et le seul qui ne soit pas durable par construction.
--
-- DEUX index partent, pas un — c'est le constat qui a émergé en vérifiant :
--
--   * `WebhookEvent_status_attempts_processedAt_idx` servait la requête de
--     candidats de la tâche : `status = FAILED AND attempts < MAX AND
--     processedAt < minAge`. Il meurt avec elle.
--
--   * `WebhookEvent_status_processedAt_idx` n'avait DÉJÀ plus de lecteur avant ce
--     lot : dans tout le dépôt, `processedAt` n'apparaît plus que dans des `data:`
--     d'écriture (la route l'horodate à COMPLETED/SKIPPED/FAILED), jamais dans un
--     `where`. Il coûtait une écriture par transition d'état pour rien.
--
-- Le seul index conservé, `[status, receivedAt]`, sert la purge à 90 jours de
-- `cleanup-pending-orders` (`status IN (COMPLETED, SKIPPED) AND receivedAt < cutoff`).
-- Les autres accès passent par `stripeEventId` (UNIQUE) ou par la clé primaire.
--
-- ⚠️ Rien n'est retiré côté COLONNES : `attempts` reste (seuil d'alerte admin) et
-- `processingStartedAt` aussi (garde de fraîcheur WEBHOOK-AUDIT-002 du pré-check
-- d'idempotence de la route, son seul consommateur désormais).

DROP INDEX "WebhookEvent_status_attempts_processedAt_idx";
DROP INDEX "WebhookEvent_status_processedAt_idx";
