import { describe, it, expect, vi, beforeEach } from "vitest";

// ============================================================================
// Hoisted mocks
// ============================================================================

const { mockCookies, mockRandomUUID } = vi.hoisted(() => ({
	mockCookies: vi.fn(),
	mockRandomUUID: vi.fn(),
}));

vi.mock("next/headers", () => ({
	cookies: mockCookies,
}));

vi.mock("@/modules/cart/constants/expiration", () => ({
	CART_EXPIRATION_DAYS: 7,
	CART_EXPIRATION_MS: 7 * 24 * 60 * 60 * 1000,
}));

import {
	getCartSessionId,
	createCartSessionId,
	getOrCreateCartSessionId,
	clearCartSessionId,
	getCartExpirationDate,
} from "../cart-session";

// ============================================================================
// Constants
// ============================================================================

const VALID_UUID_V4 = "550e8400-e29b-41d4-a716-446655440000";
const ANOTHER_VALID_UUID_V4 = "a3bb189e-8bf9-3888-9912-ace4e6543002";
// UUID v1 - version digit is 1 (not 4)
const UUID_V1 = "6ba7b810-9dad-11d1-80b4-00c04fd430c8";

const CART_SESSION_COOKIE_NAME = "cart_session";
const CART_SESSION_MAX_AGE = 60 * 60 * 24 * 7; // 7 days in seconds

// ============================================================================
// Helpers
// ============================================================================

function makeCookieStore(value?: string) {
	return {
		get: vi.fn().mockReturnValue(value !== undefined ? { value } : undefined),
		set: vi.fn(),
		delete: vi.fn(),
	};
}

// ============================================================================
// Tests: getCartSessionId
// ============================================================================

describe("getCartSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it("returns a valid UUID v4 when cookie exists with correct format", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(VALID_UUID_V4));

		const result = await getCartSessionId();

		expect(result).toBe(VALID_UUID_V4);
	});

	it("returns null when no cookie exists", async () => {
		mockCookies.mockResolvedValue(makeCookieStore());

		const result = await getCartSessionId();

		expect(result).toBeNull();
	});

	it("returns null when cookie value is an arbitrary invalid string", async () => {
		mockCookies.mockResolvedValue(makeCookieStore("invalid-string"));

		const result = await getCartSessionId();

		expect(result).toBeNull();
	});

	it("returns null when cookie value is a short alphanumeric string", async () => {
		mockCookies.mockResolvedValue(makeCookieStore("abc123"));

		const result = await getCartSessionId();

		expect(result).toBeNull();
	});

	it("returns null when cookie value is an empty string", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(""));

		const result = await getCartSessionId();

		expect(result).toBeNull();
	});

	it("returns null when cookie value is a UUID v1 (not v4)", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(UUID_V1));

		const result = await getCartSessionId();

		expect(result).toBeNull();
	});
});

// ============================================================================
// Tests: createCartSessionId
// ============================================================================

describe("createCartSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
		vi.stubGlobal("crypto", { randomUUID: mockRandomUUID });
		mockRandomUUID.mockReturnValue(VALID_UUID_V4);
	});

	it("returns the UUID generated by crypto.randomUUID", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		const result = await createCartSessionId();

		expect(result).toBe(VALID_UUID_V4);
	});

	it("calls crypto.randomUUID once", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(mockRandomUUID).toHaveBeenCalledOnce();
	});

	it("sets the cookie with the correct name and generated UUID", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			CART_SESSION_COOKIE_NAME,
			VALID_UUID_V4,
			expect.any(Object),
		);
	});

	it("sets the cookie with httpOnly: true", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ httpOnly: true }),
		);
	});

	it("sets the cookie with sameSite: lax", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ sameSite: "lax" }),
		);
	});

	it("sets the cookie with maxAge of 7 days in seconds", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ maxAge: CART_SESSION_MAX_AGE }),
		);
	});

	it("sets the cookie with path: /", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ path: "/" }),
		);
	});

	it("sets secure: false when NODE_ENV is not production", async () => {
		const original = process.env.NODE_ENV;
		vi.stubEnv("NODE_ENV", "test");

		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ secure: false }),
		);

		vi.stubEnv("NODE_ENV", original);
	});

	it("sets secure: true when NODE_ENV is production", async () => {
		vi.stubEnv("NODE_ENV", "production");

		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ secure: true }),
		);

		vi.stubEnv("NODE_ENV", "test");
	});
});

// ============================================================================
// Tests: getOrCreateCartSessionId
// ============================================================================

describe("getOrCreateCartSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
		vi.stubGlobal("crypto", { randomUUID: mockRandomUUID });
		mockRandomUUID.mockReturnValue(ANOTHER_VALID_UUID_V4);
	});

	it("returns the existing session ID when a valid cookie is present", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(VALID_UUID_V4));

		const result = await getOrCreateCartSessionId();

		expect(result).toBe(VALID_UUID_V4);
	});

	it("does not call crypto.randomUUID when a valid session already exists", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(VALID_UUID_V4));

		await getOrCreateCartSessionId();

		expect(mockRandomUUID).not.toHaveBeenCalled();
	});

	it("creates and returns a new session ID when no cookie exists", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		const result = await getOrCreateCartSessionId();

		expect(result).toBe(ANOTHER_VALID_UUID_V4);
		expect(mockRandomUUID).toHaveBeenCalledOnce();
	});

	it("creates and returns a new session ID when cookie value is not a valid UUID v4", async () => {
		const cookieStore = makeCookieStore("not-a-valid-uuid");
		mockCookies.mockResolvedValue(cookieStore);

		const result = await getOrCreateCartSessionId();

		expect(result).toBe(ANOTHER_VALID_UUID_V4);
		expect(mockRandomUUID).toHaveBeenCalledOnce();
	});

	it("sets a new cookie when existing cookie is invalid", async () => {
		const cookieStore = makeCookieStore("invalid");
		mockCookies.mockResolvedValue(cookieStore);

		await getOrCreateCartSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			CART_SESSION_COOKIE_NAME,
			ANOTHER_VALID_UUID_V4,
			expect.any(Object),
		);
	});
});

// ============================================================================
// Tests: clearCartSessionId
// ============================================================================

describe("clearCartSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it("deletes the cart_session cookie", async () => {
		const cookieStore = makeCookieStore(VALID_UUID_V4);
		mockCookies.mockResolvedValue(cookieStore);

		await clearCartSessionId();

		expect(cookieStore.delete).toHaveBeenCalledWith(CART_SESSION_COOKIE_NAME);
		expect(cookieStore.delete).toHaveBeenCalledOnce();
	});
});

// ============================================================================
// Tests: getCartExpirationDate
// ============================================================================

describe("getCartExpirationDate", () => {
	it("returns a Date approximately 7 days from now", () => {
		const before = Date.now();
		const result = getCartExpirationDate();
		const after = Date.now();

		const expectedMs = 7 * 24 * 60 * 60 * 1000;
		const resultMs = result.getTime();

		expect(resultMs).toBeGreaterThanOrEqual(before + expectedMs);
		expect(resultMs).toBeLessThanOrEqual(after + expectedMs);
	});

	it("returns a Date instance", () => {
		const result = getCartExpirationDate();

		expect(result).toBeInstanceOf(Date);
	});

	it("returns a date in the future", () => {
		const result = getCartExpirationDate();

		expect(result.getTime()).toBeGreaterThan(Date.now());
	});
});
