import { describe, it, expect, vi, beforeEach } from "vitest";

// ============================================================================
// Hoisted mocks
// ============================================================================

const { mockCookies, mockRandomUUID } = vi.hoisted(() => ({
	mockCookies: vi.fn(),
	mockRandomUUID: vi.fn(),
}));

vi.mock("next/headers", () => ({
	cookies: mockCookies,
}));

vi.mock("@/modules/wishlist/constants/expiration.constants", () => ({
	WISHLIST_EXPIRATION_DAYS: 30,
	WISHLIST_EXPIRATION_MS: 30 * 24 * 60 * 60 * 1000,
}));

import {
	isValidUuidV4,
	getWishlistSessionId,
	createWishlistSessionId,
	getOrCreateWishlistSessionId,
	clearWishlistSessionId,
	getWishlistExpirationDate,
} from "../wishlist-session";

// ============================================================================
// Constants
// ============================================================================

const VALID_UUID_V4 = "550e8400-e29b-41d4-a716-446655440000";
const ANOTHER_VALID_UUID_V4 = "a3bb189e-8bf9-3888-9912-ace4e6543002";
const UUID_V1 = "6ba7b810-9dad-11d1-80b4-00c04fd430c8";

const WISHLIST_SESSION_COOKIE_NAME = "wishlist_session";
const WISHLIST_SESSION_MAX_AGE = 60 * 60 * 24 * 30; // 30 days in seconds

// ============================================================================
// Helpers
// ============================================================================

function makeCookieStore(value?: string) {
	return {
		get: vi.fn().mockReturnValue(value !== undefined ? { value } : undefined),
		set: vi.fn(),
		delete: vi.fn(),
	};
}

// ============================================================================
// Tests: isValidUuidV4
// ============================================================================

describe("isValidUuidV4", () => {
	it("returns true for a valid UUID v4", () => {
		expect(isValidUuidV4(VALID_UUID_V4)).toBe(true);
	});

	it("returns false for a UUID v1", () => {
		expect(isValidUuidV4(UUID_V1)).toBe(false);
	});

	it("returns false for an arbitrary string", () => {
		expect(isValidUuidV4("not-a-uuid")).toBe(false);
	});

	it("returns false for an empty string", () => {
		expect(isValidUuidV4("")).toBe(false);
	});
});

// ============================================================================
// Tests: getWishlistSessionId
// ============================================================================

describe("getWishlistSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it("returns a valid UUID v4 when cookie exists with correct format", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(VALID_UUID_V4));

		const result = await getWishlistSessionId();

		expect(result).toBe(VALID_UUID_V4);
	});

	it("returns null when no cookie exists", async () => {
		mockCookies.mockResolvedValue(makeCookieStore());

		const result = await getWishlistSessionId();

		expect(result).toBeNull();
	});

	it("returns null when cookie value is an invalid string", async () => {
		mockCookies.mockResolvedValue(makeCookieStore("invalid-string"));

		const result = await getWishlistSessionId();

		expect(result).toBeNull();
	});

	it("returns null when cookie value is empty", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(""));

		const result = await getWishlistSessionId();

		expect(result).toBeNull();
	});

	it("returns null when cookie value is a UUID v1", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(UUID_V1));

		const result = await getWishlistSessionId();

		expect(result).toBeNull();
	});
});

// ============================================================================
// Tests: createWishlistSessionId
// ============================================================================

describe("createWishlistSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
		vi.stubGlobal("crypto", { randomUUID: mockRandomUUID });
		mockRandomUUID.mockReturnValue(VALID_UUID_V4);
	});

	it("returns the UUID generated by crypto.randomUUID", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		const result = await createWishlistSessionId();

		expect(result).toBe(VALID_UUID_V4);
	});

	it("calls crypto.randomUUID once", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(mockRandomUUID).toHaveBeenCalledOnce();
	});

	it("sets the cookie with the correct name and generated UUID", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			WISHLIST_SESSION_COOKIE_NAME,
			VALID_UUID_V4,
			expect.any(Object),
		);
	});

	it("sets the cookie with httpOnly: true", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ httpOnly: true }),
		);
	});

	it("sets the cookie with sameSite: lax", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ sameSite: "lax" }),
		);
	});

	it("sets the cookie with maxAge of 30 days in seconds", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ maxAge: WISHLIST_SESSION_MAX_AGE }),
		);
	});

	it("sets the cookie with path: /", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ path: "/" }),
		);
	});

	it("sets secure: false when NODE_ENV is not production", async () => {
		vi.stubEnv("NODE_ENV", "test");
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ secure: false }),
		);
	});

	it("sets secure: true when NODE_ENV is production", async () => {
		vi.stubEnv("NODE_ENV", "production");
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		await createWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			expect.any(String),
			expect.any(String),
			expect.objectContaining({ secure: true }),
		);

		vi.stubEnv("NODE_ENV", "test");
	});
});

// ============================================================================
// Tests: getOrCreateWishlistSessionId
// ============================================================================

describe("getOrCreateWishlistSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
		vi.stubGlobal("crypto", { randomUUID: mockRandomUUID });
		mockRandomUUID.mockReturnValue(ANOTHER_VALID_UUID_V4);
	});

	it("returns the existing session ID when a valid cookie is present", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(VALID_UUID_V4));

		const result = await getOrCreateWishlistSessionId();

		expect(result).toBe(VALID_UUID_V4);
	});

	it("does not call crypto.randomUUID when a valid session already exists", async () => {
		mockCookies.mockResolvedValue(makeCookieStore(VALID_UUID_V4));

		await getOrCreateWishlistSessionId();

		expect(mockRandomUUID).not.toHaveBeenCalled();
	});

	it("creates and returns a new session ID when no cookie exists", async () => {
		const cookieStore = makeCookieStore();
		mockCookies.mockResolvedValue(cookieStore);

		const result = await getOrCreateWishlistSessionId();

		expect(result).toBe(ANOTHER_VALID_UUID_V4);
		expect(mockRandomUUID).toHaveBeenCalledOnce();
	});

	it("creates a new session ID when cookie value is not a valid UUID v4", async () => {
		const cookieStore = makeCookieStore("not-a-valid-uuid");
		mockCookies.mockResolvedValue(cookieStore);

		const result = await getOrCreateWishlistSessionId();

		expect(result).toBe(ANOTHER_VALID_UUID_V4);
		expect(mockRandomUUID).toHaveBeenCalledOnce();
	});

	it("sets a new cookie when existing cookie is invalid", async () => {
		const cookieStore = makeCookieStore("invalid");
		mockCookies.mockResolvedValue(cookieStore);

		await getOrCreateWishlistSessionId();

		expect(cookieStore.set).toHaveBeenCalledWith(
			WISHLIST_SESSION_COOKIE_NAME,
			ANOTHER_VALID_UUID_V4,
			expect.any(Object),
		);
	});
});

// ============================================================================
// Tests: clearWishlistSessionId
// ============================================================================

describe("clearWishlistSessionId", () => {
	beforeEach(() => {
		vi.clearAllMocks();
	});

	it("deletes the wishlist_session cookie", async () => {
		const cookieStore = makeCookieStore(VALID_UUID_V4);
		mockCookies.mockResolvedValue(cookieStore);

		await clearWishlistSessionId();

		expect(cookieStore.delete).toHaveBeenCalledWith(WISHLIST_SESSION_COOKIE_NAME);
		expect(cookieStore.delete).toHaveBeenCalledOnce();
	});
});

// ============================================================================
// Tests: getWishlistExpirationDate
// ============================================================================

describe("getWishlistExpirationDate", () => {
	it("returns a Date approximately 30 days from now", () => {
		const before = Date.now();
		const result = getWishlistExpirationDate();
		const after = Date.now();

		const expectedMs = 30 * 24 * 60 * 60 * 1000;
		const resultMs = result.getTime();

		expect(resultMs).toBeGreaterThanOrEqual(before + expectedMs);
		expect(resultMs).toBeLessThanOrEqual(after + expectedMs);
	});

	it("returns a Date instance", () => {
		const result = getWishlistExpirationDate();

		expect(result).toBeInstanceOf(Date);
	});

	it("returns a date in the future", () => {
		const result = getWishlistExpirationDate();

		expect(result.getTime()).toBeGreaterThan(Date.now());
	});
});
