-- ============================================================================
-- OrderAction enum extension : CREDIT_NOTE_GENERATED
-- Audit avoirs 2026-05-28 — EINV-CREDIT-010
-- ============================================================================
--
-- Contexte :
--   L'enum OrderAction contient `INVOICE_VOIDED` (full void de la facture
--   originale = cas refund total) et `CREDIT_NOTE_FAILED` (échec émission)
--   mais aucun event distinct pour l'émission EFFECTIVE d'un avoir.
--
--   Avec l'arrivée du support refund partiel (EINV-CREDIT-001), un avoir peut
--   être émis SANS voider la facture originale (qui reste comptablement
--   valide pour la part non remboursée). On a donc besoin de distinguer :
--
--     - INVOICE_VOIDED       → facture invalidée (full refund / cancel)
--     - CREDIT_NOTE_GENERATED → avoir émis (partiel OU total, comptable)
--
--   Pour un full refund, les DEUX events sont émis dans la même transaction :
--   INVOICE_VOIDED tracé la fin de vie de la facture, CREDIT_NOTE_GENERATED
--   tracé l'émission de l'avoir séquentiel (A-YYYY-NNNNN).
--
--   Conformité Art. 272-I CGI : l'avoir est une obligation pour TOUT
--   remboursement (partiel ou total) sur facture émise.
-- ============================================================================

ALTER TYPE "OrderAction" ADD VALUE 'CREDIT_NOTE_GENERATED';
