-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "accessToken" SET DATA TYPE TEXT;
ALTER TABLE "Account" ALTER COLUMN "refreshToken" SET DATA TYPE TEXT;
ALTER TABLE "Account" ALTER COLUMN "idToken" SET DATA TYPE TEXT;
