-- Résorption d'un drift schema.prisma <-> historique de migrations
-- (audit schéma 2026-07-26, finding F1).
--
-- La migration 20260511140000_drop_order_review_request_sent_at a exécuté
--   ALTER TABLE "Order" DROP COLUMN "reviewRequestSentAt";
-- et AUCUNE migration ultérieure ne l'a re-créée. Pourtant schema.prisma la
-- déclarait toujours, et `modules/reviews/services/send-review-requests.service.ts`
-- la lisait et l'écrivait.
--
-- Pourquoi c'est resté invisible ~2,5 mois : le service était dormant (pas de
-- route cron, pas d'entrée vercel.json), et le setup des tests d'intégration
-- applique `db push` — qui recrée la colonne depuis schema.prisma au lieu de
-- rejouer les migrations. Sur une base reconstruite par `migrate deploy`, la
-- colonne n'existait donc pas.
--
-- Décision : aligner le code sur la base (la colonne reste absente) et retirer
-- l'émetteur d'email « demande d'avis », dormant depuis le right-sizing du
-- volume e-mail. Le reste du module reviews (soumission storefront, modération
-- admin, stats agrégées, JSON-LD) est intact.
--
-- Ce DDL est un NO-OP sur une base à jour des migrations. Il n'est là que pour
-- rattraper une base où un `db push` (dev, intégration) aurait recréé la
-- colonne entre-temps — et pour que le prochain audit trouve la trace écrite
-- du drift au lieu de reposer la question.
--
-- Garde-fou durable : test/contract/schema-migration-parity.contract.test.ts.

ALTER TABLE "Order" DROP COLUMN IF EXISTS "reviewRequestSentAt";
